package com.dev.ksp_processor

import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.processing.KSPLogger
import com.google.devtools.ksp.processing.Resolver
import com.google.devtools.ksp.processing.SymbolProcessor
import com.google.devtools.ksp.symbol.KSAnnotated
import com.google.devtools.ksp.symbol.KSClassDeclaration
import com.google.devtools.ksp.validate
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.TypeSpec
import com.squareup.kotlinpoet.ksp.writeTo

class InjectWithProcessor(
    private val codeGenerator: CodeGenerator,
    private val logger: KSPLogger
) : SymbolProcessor {

    companion object {
        private const val INJECT_WITH_ANNOTATION = "com.dev.annotation.InjectWith"
    }

    override fun process(resolver: Resolver): List<KSAnnotated> {
        val symbols = resolver.getSymbolsWithAnnotation(INJECT_WITH_ANNOTATION)
        val unableToProcess = symbols.filterNot { it.validate() }.toList()

        symbols
            .filter { it is KSClassDeclaration && it.validate() }
            .forEach { symbol ->
                val classDeclaration = symbol as KSClassDeclaration
                generateCode(classDeclaration)
            }

        return unableToProcess
    }

    private fun generateCode(classDeclaration: KSClassDeclaration) {
        val packageName = classDeclaration.packageName.asString()
        val className = classDeclaration.simpleName.asString()
        val generatedClassName = "${className}KspGenerated"

        logger.info("Generating $generatedClassName for $className")

        val fileSpec = FileSpec.builder(packageName, generatedClassName)
            .addType(
                TypeSpec.classBuilder(generatedClassName)
                    .addKdoc("Generated by KSP for $className")
                    .build()
            )
            .build()

        fileSpec.writeTo(
            codeGenerator = codeGenerator,
            dependencies = Dependencies(
                aggregating = false,
                classDeclaration.containingFile!!
            )
        )
    }
}
